"""AI-powered meeting summarization module."""
import os
from anthropic import Anthropic
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


class Summarizer:
    """Summarizer for generating meeting summaries using Claude AI."""

    def __init__(self, api_key=None):
        """
        Initialize the summarizer.

        Args:
            api_key: Anthropic API key (if not provided, will use env var)
        """
        self.api_key = api_key or os.getenv('ANTHROPIC_API_KEY')
        if not self.api_key:
            raise ValueError(
                "Anthropic API key not found. Please set ANTHROPIC_API_KEY "
                "environment variable or pass api_key parameter."
            )
        self.client = Anthropic(api_key=self.api_key)

    def generate_summary(self, transcript, meeting_title=None, custom_prompt=None):
        """
        Generate a summary of the meeting transcript.

        Args:
            transcript: The meeting transcript text
            meeting_title: Optional meeting title for context
            custom_prompt: Optional custom prompt for summarization

        Returns:
            Dictionary containing summary and key points
        """
        if custom_prompt:
            prompt = custom_prompt
        else:
            prompt = self._build_default_prompt(transcript, meeting_title)

        print("Generating meeting summary with AI...")

        try:
            message = self.client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=2000,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )

            summary = message.content[0].text
            print("Summary generated successfully!")

            return {
                'summary': summary,
                'model': 'claude-3-5-sonnet-20241022'
            }

        except Exception as e:
            print(f"Error generating summary: {e}")
            raise

    def _build_default_prompt(self, transcript, meeting_title):
        """Build the default prompt for summarization."""
        title_context = f"Meeting Title: {meeting_title}\n\n" if meeting_title else ""

        prompt = f"""{title_context}Please analyze the following meeting transcript and provide a comprehensive summary with the following sections:

1. **Executive Summary**: A brief 2-3 sentence overview of the meeting
2. **Key Discussion Points**: Main topics discussed (bullet points)
3. **Decisions Made**: Any decisions or conclusions reached
4. **Action Items**: Tasks assigned with responsible parties if mentioned
5. **Next Steps**: Follow-up actions or future meeting plans

Transcript:
{transcript}

Please format your response clearly with headers for each section."""

        return prompt

    def save_summary(self, summary_data, output_path):
        """
        Save the summary to a file.

        Args:
            summary_data: Dictionary containing summary information
            output_path: Path to save the summary

        Returns:
            Path to the saved summary file
        """
        os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else '.', exist_ok=True)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("=== MEETING SUMMARY ===\n\n")
            f.write(summary_data['summary'])
            f.write(f"\n\n---\nGenerated by: {summary_data['model']}\n")

        print(f"Summary saved to: {output_path}")
        return output_path

    def summarize_and_save(self, transcript, output_dir='summaries',
                          meeting_title=None, filename=None):
        """
        Convenience method to summarize and save in one step.

        Args:
            transcript: The meeting transcript text
            output_dir: Directory to save summaries
            meeting_title: Optional meeting title
            filename: Optional custom filename

        Returns:
            Tuple of (summary_path, summary_text)
        """
        # Generate summary
        summary_data = self.generate_summary(transcript, meeting_title)

        # Generate filename if not provided
        if filename is None:
            from datetime import datetime
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"summary_{timestamp}.txt"

        output_path = os.path.join(output_dir, filename)

        # Save
        self.save_summary(summary_data, output_path)

        return output_path, summary_data['summary']
